
package com.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BaseicQueryService", targetNamespace = "http://service.server.com/", wsdlLocation = "http://localhost:9999/baseQueryService?wsdl")
public class BaseicQueryService
    extends Service
{

    private final static URL BASEICQUERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASEICQUERYSERVICE_EXCEPTION;
    private final static QName BASEICQUERYSERVICE_QNAME = new QName("http://service.server.com/", "BaseicQueryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/baseQueryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASEICQUERYSERVICE_WSDL_LOCATION = url;
        BASEICQUERYSERVICE_EXCEPTION = e;
    }

    public BaseicQueryService() {
        super(__getWsdlLocation(), BASEICQUERYSERVICE_QNAME);
    }

    public BaseicQueryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASEICQUERYSERVICE_QNAME, features);
    }

    public BaseicQueryService(URL wsdlLocation) {
        super(wsdlLocation, BASEICQUERYSERVICE_QNAME);
    }

    public BaseicQueryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASEICQUERYSERVICE_QNAME, features);
    }

    public BaseicQueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseicQueryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BaseicQuery
     */
    @WebEndpoint(name = "BaseicQueryPort")
    public BaseicQuery getBaseicQueryPort() {
        return super.getPort(new QName("http://service.server.com/", "BaseicQueryPort"), BaseicQuery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseicQuery
     */
    @WebEndpoint(name = "BaseicQueryPort")
    public BaseicQuery getBaseicQueryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.com/", "BaseicQueryPort"), BaseicQuery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASEICQUERYSERVICE_EXCEPTION!= null) {
            throw BASEICQUERYSERVICE_EXCEPTION;
        }
        return BASEICQUERYSERVICE_WSDL_LOCATION;
    }

}
